h_Words	BYTE "SCOOTER",	0
		BYTE "HUNGER", 0
		BYTE "CHILI", 0
		BYTE "YOKE", 0
		BYTE "VIOLET", 0
		BYTE "MYTHOLOGY", 0
		BYTE "KNOCKOUT", 0
		BYTE "CHALLENGE", 0
		BYTE "NEON", 0
		BYTE "PUNISH", 0
		BYTE "LUST", 0
		BYTE "YAWN", 0
		BYTE "WELD", 0
		BYTE 0			